# Data Wrangling Challenge
### Pull and manipulate the API data

The point of this exercise is to try data enrichment with data from external APIs. We are going to take data about car crashes in Monroe County, Indiana from 2003 to 2015 and try to figure out the weather during the accident and how many bars there are in the area. We will work with two different APIs during this challenge:

- Foursquare API
- Visual Crossing API

We will try to find correlations between the severity of crash and weather/number of bars in the area. To indicate the severity of a crash, we will use column `Injury Type`.

## Data

The data for this exercise can be found [here](https://drive.google.com/file/d/1_KF9oIJV8cB8i3ngA4JPOLWIE_ETE6CJ/view?usp=sharing).

Just run the cells below to get your data ready. Little help from us.

In [48]:
import pandas as pd
from pandas import json_normalize
import os
import config

In [13]:
data = pd.read_csv("monroe-county-crash-data2003-to-2015.csv", encoding="unicode_escape")
# ========================
# preparing data
data.dropna(subset=['Latitude', 'Longitude'], inplace=True)
# creation of variable with lon and lat together
data['ll'] = data['Latitude'].astype(str) + ',' + data['Longitude'].astype(str)
data = data[data['ll'] != '0.0,0.0']
print(data.shape)
data.head()

(49005, 13)

,Master Record Number,Year,Month,Day,Weekend?,Hour,Collision Type,Injury Type,Primary Factor,Reported_Location,Latitude,Longitude,ll
0,902363382,2015,1,5,Weekday,0.0,2-Car,No injury/unknown,OTHER (DRIVER) - EXPLAIN IN NARRATIVE,1ST & FESS,39.159207,-86.525874,"39.15920668,-86.52587356"
1,902364268,2015,1,6,Weekday,1500.0,2-Car,No injury/unknown,FOLLOWING TOO CLOSELY,2ND & COLLEGE,39.161440,-86.534848,"39.16144,-86.534848"
2,902364412,2015,1,6,Weekend,2300.0,2-Car,Non-incapacitating,DISREGARD SIGNAL/REG SIGN,BASSWOOD & BLOOMFIELD,39.149780,-86.568890,"39.14978027,-86.56889006"
3,902364551,2015,1,7,Weekend,900.0,2-Car,Non-incapacitating,FAILURE TO YIELD RIGHT OF WAY,GATES & JACOBS,39.165655,-86.575956,"39.165655,-86.57595635"
4,902364615,2015,1,7,Weekend,1100.0,2-Car,No injury/unknown,FAILURE TO YIELD RIGHT OF WAY,W 3RD,39.164848,-86.579625,"39.164848,-86.57962482"

In [20]:
data.keys() # Now we need WEATHER and BARS IN AREA for that date

Index(['Master Record Number', 'Year', 'Month', 'Day', 'Weekend?', 'Hour',
       'Collision Type', 'Injury Type', 'Primary Factor', 'Reported_Location',
       'Latitude', 'Longitude', 'll'],
      dtype='object')

In [23]:
# params = dict(client_id = foursquare_id
#               client_secret=foursquare_secret
#               v="20180323"
#               ll = ll
#               query="bar"
#               limit=50, radius=5000)

# return requests.get

                             ll
0      39.15920668,-86.52587356
1           39.16144,-86.534848
2      39.14978027,-86.56889006
3        39.165655,-86.57595635
4        39.164848,-86.57962482
...                         ...
53344  39.00427482,-86.58137523
53345      39.002752,-86.463856
53346  38.99232624,-86.53725171
53347       38.99152,-86.448784
53348      38.990848,-86.368864

[49005 rows x 1 columns]

# Foursquare API

Foursquare API documentation is [here](https://developer.foursquare.com/)

1. Start a foursquare application and get your keys.
2. For each crash, create the function **get_venues** that will pull bars in the radius of 5km around the crash

#### example
`get_venues('48.146394, 17.107969')`

3. Find a relationship (if there is any) between number of bars in the area and severity of the crash.

HINTs: 
- check out python package "foursquare" (no need to send HTTP requests directly with library `requests`)
- **categoryId** for bars and nightlife needs to be found in the [foursquare API documentation](https://developer.foursquare.com/docs/api-reference/venues/search/)

In [11]:
#set the keys
foursquare_id = config.FOURSQUARE_CLIENT_ID
foursquare_secret = config.FOURSQUARE_CLIENT_SECRET

In [39]:
lat_long = "39.16144,-86.534848"

In [46]:
url_venues = "https://api.foursquare.com/v2/venues/search?near=39.122352,-86.5712&client_id="+foursquare_id+"&client_secret="+foursquare_secret+"&v=20200731"

In [41]:
import requests as re
res = re.get(url_venues)
res

In [65]:
venues_json = res.json()
type(venues_json) # VENUES DONE

dict

In [66]:
venues_json.keys()

dict_keys(['meta', 'response'])

In [74]:
venues_json["response"].keys()

dict_keys(['venues', 'confident', 'geocode'])

In [76]:
venues = json_normalize(venues_json["response"]["venues"])

,id,name,categories,referralId,hasPerk,location.lat,location.lng,location.labeledLatLngs,location.cc,location.city,...,location.crossStreet,location.postalCode,location.neighborhood,venuePage.id,delivery.id,delivery.url,delivery.provider.name,delivery.provider.icon.prefix,delivery.provider.icon.sizes,delivery.provider.icon.name
0,569fa53c498ec3cca20ebf6b,Cook Vascular Training Center,"[{'id': '4bf58dd8d48988d124941735', 'name': 'O...",v-1632358598,False,39.166258,-86.534140,"[{'label': 'display', 'lat': 39.16625761663199...",US,Bloomington,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4afdccbff964a520f92a22e3,Kroger,"[{'id': '52f2ab2ebcbc57f1066b8b46', 'name': 'S...",v-1632358598,False,39.159901,-86.535746,"[{'label': 'display', 'lat': 39.1599011, 'lng'...",US,Bloomington,...,at W. 2nd,47403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,59ced309a9fe123f1ca6a21e,Friendly Beasts Cider Company,[],v-1632358598,False,39.161694,-86.535866,"[{'label': 'display', 'lat': 39.161694, 'lng':...",US,Bloomington,...,B-line and 2nd,47403,Downtown Bloomington,479158422,NaN,NaN,NaN,NaN,NaN,NaN
3,5f494a60aefbc30ef2c41480,Jeff’s Warehouse,"[{'id': '4bf58dd8d48988d101951735', 'name': 'T...",v-1632358598,False,39.162063,-86.535121,"[{'label': 'display', 'lat': 39.162063, 'lng':...",US,Bloomington,...,NaN,47403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4c796ce2566db60ce9eb440e,Furniture Exchange,"[{'id': '4bf58dd8d48988d1f8941735', 'name': 'F...",v-1632358598,False,39.162097,-86.535502,"[{'label': 'display', 'lat': 39.16209699999999...",US,Bloomington,...,NaN,47404,NaN,36587240,NaN,NaN,NaN,NaN,NaN,NaN
5,4e31c4302fb6ede816e38555,Redbox,"[{'id': '4bf58dd8d48988d126951735', 'name': 'V...",v-1632358598,False,39.161290,-86.534952,"[{'label': 'display', 'lat': 39.16129, 'lng': ...",US,Bloomington,...,NaN,47403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,4e8cd95755032ad219e7148f,US Post Office,"[{'id': '4bf58dd8d48988d172941735', 'name': 'P...",v-1632358598,False,39.160528,-86.534063,"[{'label': 'entrance', 'lat': 39.160495, 'lng'...",US,Bloomington,...,1st & Walnut St,47401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,4ba1174bf964a520df9637e3,Wendy’s,"[{'id': '4bf58dd8d48988d16e941735', 'name': 'F...",v-1632358598,False,39.161105,-86.535760,"[{'label': 'display', 'lat': 39.16110473161429...",US,Bloomington,...,NaN,47403,NaN,NaN,1684878,https://www.grubhub.com/restaurant/wendys-221-...,grubhub,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_grubhub_20180129.png
8,5e8fe51b8655b4000873b42e,Happy Thai Restaurant,"[{'id': '4bf58dd8d48988d149941735', 'name': 'T...",v-1632358598,False,39.160348,-86.533324,"[{'label': 'display', 'lat': 39.160348, 'lng':...",US,Bloomington,...,NaN,47401,NaN,NaN,2100167,https://www.grubhub.com/restaurant/happy-thai-...,grubhub,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_grubhub_20180129.png
9,4dc5ae96e4cd169dc653b749,The Chocolate Moose,"[{'id': '4bf58dd8d48988d1c9941735', 'name': 'I...",v-1632358598,False,39.162665,-86.533564,"[{'label': 'display', 'lat': 39.162665, 'lng':...",US,Bloomington,...,NaN,47401,NaN,NaN,797018,https://www.grubhub.com/restaurant/the-chocola...,grubhub,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_grubhub_20180129.png
10,4c26839bf3859c7487676588,Peach Garden,"[{'id': '4bf58dd8d48988d145941735', 'name': 'C...",v-1632358598,False,39.159931,-86.535561,"[{'label': 'display', 'lat': 39.15993118286133...",US,Bloomington,...,at 1st,47403,NaN,NaN,260643,https://www.grubhub.com/restaurant/peach-garde...,grubhub,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_grubhub_20180129.png
11,512c092ce4b0ccaae56fe010,My Thai Express,"[{'id': '4bf58dd8d48988d149941735', 'name': 'T...",v-1632358598,False,39.160310,-86.533363,"[{'label': 'display', 'lat': 39.16030997333662...",US,Bloomington,...,NaN,47401,NaN,50205735,NaN,NaN,NaN,NaN,NaN,NaN
12,4b904659f964a520a98033e3,Arby's,"[{'id': '4bf58dd8d48988d16e941735', 'name': 'F...",v-1632358598,False,39.160007,-86.533274,"[{'label': 'display', 'lat': 39.1600066343555,...",US,Bloomington,...,NaN,47401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,4afa0d6af964a5205d1622e3,Grazie! Italiano,"[{'id': '4bf58dd8d48988d110941735', 'name': 'I...",v-1632358598,False,39.167681,-86.533926,"[{'label': 'display', 'lat': 39.16768145607438...",US,Bloomington,...,Walnut & West 6th Street,47404,NaN,32899173,NaN,NaN,NaN,NaN,NaN,NaN
14,4b2050c0f964a520803024e3,Big Red Outlet,"[{'id': '4bf58dd8d48988d186941735', 'name': 'L...",v-1632358598,False,39.161554,-86.533483,"[{'label': 'display', 'lat': 39.16155392244062...",US,Bloomington,...,at 2nd St,47401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,4af38d33f964a5208eee21e3,Malibu Grill,"[{'id': '4bf58dd8d48988d157941735', 'name': 'N...",v-1632358598,False,39.166865,-86.533579,"[{'label': 'display', 'lat': 39.1668649358185,...",US,Bloomington,...,Kirkwood Ave,47404,NaN,59602343,NaN,NaN,NaN,NaN,NaN,NaN
16,4aeda1b2f964a520f1cd21e3,Uptown Cafe,"[{'id': '4bf58dd8d48988d17a941735', 'name': 'C...",v-1632358598,False,39.166434,-86.533349,"[{'label': 'display', 'lat': 39.16643420713071...",US,Bloomington,...,NaN,47408,NaN,530285805,NaN,NaN,NaN,NaN,NaN,NaN
17,593e19af7269fe61569c1dcf,Bluetip,"[{'id': '4bf58dd8d48988d11d941735', 'name': 'S...",v-1632358598,False,39.162300,-86.535200,"[{'label': 'display', 'lat': 39.1623, 'lng': -...",US,Bloomington,...,NaN,47403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,4e80b6808231841cb8e40cdd,United Way of Monroe County,"[{'id': '4bf58dd8d48988d124941735', 'name': 'O...",v-1632358598,False,39.161761,-86.534532,"[{'label': 'display', 'lat': 39.16176094003290...",US,Bloomington,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,56fd6843498eee405666ff3f,Hopscotch Coffee,"[{'id': '4bf58dd8d48988d1e0931735', 'name': 'C...",v-1632358598,False,39.161730,-86.533679,"[{'label': 'display', 'lat': 39.16173041757003...",US,Bloomington,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,4b7efb4bf964a520140e30e3,Rally's,"[{'id': '4bf58dd8d48988d16e941735', 'name': 'F...",v-1632358598,False,39.159545,-86.534115,"[{'label': 'display', 'lat': 39.15954492925336...",US,Bloomington,...,1st St.,47401,NaN,NaN,2540226,https://www.grubhub.com/restaurant/rallys-550-...,grubhub,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_grubhub_20180129.png
21,4f32bfcb19836c91c7f65186,Spectrum Studios,"[{'id': '4bf58dd8d48988d1e2931735', 'name': 'A...",v-1632358598,False,39.162121,-86.535187,"[{'label': 'display', 'lat': 39.1621208190918,...",US,Bloomington,...,NaN,47403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4b842d25f964a520ad2531e3,Sahara Mart,"[{'id': '4bf58dd8d48988d118951735', 'name': 'G...",v-1632358598,False,39.161355,-86.533177,"[{'label': 'display', 'lat': 39.16135483028275...",US,Bloomington,...,NaN,47401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,4b60e357f964a520ddff29e3,Courtyard Bloomington,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",v-1632358598,False,39.163829,-86.535389,"[{'label': 'display', 'lat': 39.1638289, 'lng'...",US,Bloomington,...,NaN,47403,NaN,74982147,NaN,NaN,NaN,NaN,NaN,NaN
24,5e9e9d6317ca5f0007ea4b1f,KeyMe Locksmiths,"[{'id': '52f2ab2ebcbc57f1066b8b1e', 'name': 'L...",v-1632358598,False,39.159900,-86.535700,"[{'label': 'display', 'lat': 39.1599, 'lng': -...",US,Bloomington,...,NaN,47403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,591c5ea16eda0263a3166d9e,Kroger Pharmacy,"[{'id': '4bf58dd8d48988d10f951735', 'name': 'P...",v-1632358598,False,39.160132,-86.535545,"[{'label': 'display', 'lat': 39.1601317, 'lng'...",US,Bloomington,...,NaN,47403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,542a3a5a498e0b0d25839f88,Sofra Cafe,"[{'id': '4f04af1f2fb6e1c99f3db0bb', 'name': 'T...",v-1632358598,False,39.163052,-86.533767,"[{'label': 'display', 'lat': 39.16305248112930...",US,Bloomington,...,NaN,47401,NaN,98212400,NaN,NaN,NaN,NaN,NaN,NaN
27,592908018d0a535029fbeb52,iMechanic,"[{'id': '4f04afc02fb6e1c99f3db0bc', 'name': 'M...",v-1632358598,False,39.161900,-86.533290,"[{'label': 'display', 'lat': 39.1619, 'lng': -...",US,Bloomington,...,NaN,47401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,4d1d0fd72eb1f04d1d3dd3c1,Therapeutic Massage & Bodyworks,[],v-1632358598,False,39.162292,-86.536707,"[{'label': 'display', 'lat': 39.16229226395851...",US,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,4cc0640797bc721ef4218b67,Hoosier CrossFit,"[{'id': '4bf58dd8d48988d176941735', 'name': 'G...",v-1632358598,False,39.162509,-86.535575,"[{'label': 'display', 'lat': 39.162509, 'lng':...",US,Bloomington,...,2nd Street,47403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# need to use ll, this median ll doesn't work. Need to correlate

# Visual Crossing API

Virtual Crossing API documentation is [here](https://www.visualcrossing.com/resources/documentation/)

1. Sign up for FREE api key if you haven't done that before.
2. For each crush, get the weather for the location and date.
3. Find a relationship between the weather and severity of the crash.

Hints:

* randomly sample only 250 or so (due to API limits), or pull weather only for smaller sample of crashes
* for sending HTTP requests check out "requests" library [here](http://docs.python-requests.org/en/master/)

In [193]:
import requests
import time
api_key = os.environ[]