In [6]:
import pandas as pd
pd.set_option("display.max_columns", None)
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Import data (flights january, november, december and flight_test)

In [7]:
df_nov_dec = pd.read_csv("data/flights_2019_nov_dec.csv")
df_jan = pd.read_csv("data/flights_2019_jan_raw.csv")
df_weather = pd.read_csv("data/WeatherEvents_2018_2020.csv")
df_passengers = pd.read_csv("data/passengers_nov_dec_jan_raw.csv")
df_fuel = pd.read_csv("data/fuel_comsumption_2018.csv")

In [8]:
# Flights df
df = pd.concat([df_nov_dec, df_jan]).reset_index().drop(columns=["index"])

In [21]:
flights_raw = df.copy()

### NA Values fixing

In [15]:
# make DF with delay columns for referencing
df_delays = pd.DataFrame()
df_delays = flights_raw[["carrier_delay","weather_delay","nas_delay","security_delay","late_aircraft_delay","arr_delay"]]

In [24]:
# Null value function
def missing(x):
    n_missing = x.isnull().sum().sort_values(ascending=False)
    p_missing = (x.isnull().sum()/x.isnull().count()).sort_values(ascending=False)
    missing_ = pd.concat([n_missing, p_missing],axis=1, keys = ['number','percent'])
    missing_ = missing_[missing_["percent"] > 0]
    return missing_

In [25]:
missing(flights_raw)

                      number   percent
no_name              2644325  1.000000
total_add_gtime      2627839  0.993766
first_dep_time       2627838  0.993765
longest_add_gtime    2627838  0.993765
cancellation_code    2605974  0.985497
late_aircraft_delay  2178457  0.823823
security_delay       2178457  0.823823
nas_delay            2178457  0.823823
weather_delay        2178457  0.823823
carrier_delay        2178457  0.823823
actual_elapsed_time    43685  0.016520
arr_delay              43685  0.016520
air_time               43685  0.016520
wheels_on              39464  0.014924
taxi_in                39464  0.014924
arr_time               39464  0.014924
taxi_out               37886  0.014327
wheels_off             37886  0.014327
dep_delay              36956  0.013976
dep_time               36952  0.013974
tail_num                7808  0.002953
crs_elapsed_time           9  0.000003

In [ ]:
flights_raw = flights_raw.drop(columns = ['no_name', 'longest_add_gtime','total_add_gtime'
                                          ,'first_dep_time','late_aircraft_delay','security_delay',
                                          'nas_delay','weather_delay','carrier_delay','cancellation_code','tail_num'],axis=1)

In [60]:
# fill the remaining NA values
df['dep_time'] = df['dep_time'].fillna(df['dep_time'].mean())
df['dep_delay'] = df['dep_delay'].fillna(df['dep_delay'].mean())
df['taxi_out'] = df['taxi_out'].fillna(df['taxi_out'].mean())
df['wheels_off'] = df['wheels_off'].fillna(df['wheels_off'].mean())
df['wheels_on'] = df['wheels_on'].fillna(df['wheels_off'].mean())
df['taxi_in'] = df['taxi_in'].fillna(df['taxi_in'].mean())
df['arr_time'] = df['arr_time'].fillna(df['arr_time'].mean())
df['arr_delay'] = df['arr_delay'].fillna(df['arr_delay'].mean())
df['actual_elapsed_time'] = df['actual_elapsed_time'].fillna(df['actual_elapsed_time'].mean())
df['crs_elapsed_time'] = df['crs_elapsed_time'].fillna(df['crs_elapsed_time'].mean())
df['air_time'] = df['air_time'].fillna(df['air_time'].mean())

In [61]:
# renaming mkt_unique_carrier with their full airline name for plotting
# will change to numerical dummies later for model creation
df.groupby(by="mkt_unique_carrier").count()

,fl_date,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance
mkt_unique_carrier,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
AA,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080,862080
AS,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048,179048
B6,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380,124380
DL,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858,724858
F9,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361,54361
G4,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568,42568
HA,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386,38386
NK,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947,80947
UA,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061,644061
VX,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720,5720
WN,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260,568260

## Mapping airport/airline names

In [62]:
# Mapping file for airport names
import json
with open('airport_names_dict.txt') as f: # my map
    data = f.read()
airport_names_dict = json.loads(data)

In [63]:
# Adding new column with full airport names
df["airport_names"] = df["origin"]
df["airport_names"] = df['airport_names'].map(airport_names_dict)

In [64]:
# Mapping file for airline names
import json
with open('airline_names_dict.txt') as f: # my map
    data2 = f.read()
airline_names_dict = json.loads(data2)

In [65]:
# Adding new column with full airline names
df["airline_names"] = df["mkt_carrier"]
df["airline_names"] = df['airline_names'].map(airline_names_dict)

## save files to csv - filesizes each ~900mb

In [66]:
df.shape

(3324669, 33)

In [70]:
flights_2019_july_CLEAN = df[(df['fl_date'] > '2019-07-01') & (df['fl_date'] <= '2019-07-31')]
flights_2019_aug_CLEAN = df[(df['fl_date'] > '2019-08-01') & (df['fl_date'] <= '2019-08-31')]
flights_2019_jan_CLEAN = df[(df['fl_date'] > '2018-01-01') & (df['fl_date'] <= '2018-01-31')]
flights_2019_nov_CLEAN = df[(df['fl_date'] > '2018-11-01') & (df['fl_date'] <= '2018-11-30')]
flights_2019_dec_CLEAN = df[(df['fl_date'] > '2018-12-01') & (df['fl_date'] <= '2018-12-31')]

In [71]:
print(flights_2019_july_CLEAN.shape)
print(flights_2019_aug_CLEAN.shape)
print(flights_2019_nov_CLEAN.shape)
print(flights_2019_dec_CLEAN.shape)
print(flights_2019_jan_CLEAN.shape)

(695238, 33)
(693078, 33)
(617345, 33)
(632306, 33)
(582096, 33)

In [72]:
df.to_csv("data/flights_2019_july_CLEAN.csv") # summer months for weather checks
df.to_csv("data/flights_2019_aug_CLEAN.csv")
df.to_csv("data/flights_2019_jan_CLEAN.csv") # winter months for modeling
df.to_csv("data/flights_2019_nov_CLEAN.csv")
df.to_csv("data/flights_2019_dec_CLEAN.csv")