# XML exercise

Using data from [**mondial database**](https://drive.google.com/file/d/14lFT4nWHgwN36ij4XZh6OUuup-K9qLgR/view?usp=sharing) find the answers to following questions:

1. 10 countries with the lowest infant mortality rates
2. 10 cities with the largest population
3. name and country of a) longest river, b) largest lake and c) airport at highest elevation

In [47]:
import xml.etree.ElementTree as ET
import pandas as pd
import json
from pandas import json_normalize

In [2]:
tree = ET.parse('mondial.xml')

In [3]:
root = tree.getroot()
root

In [4]:
print(root.tag)
print(root.attrib)
print(len(root))

mondial
{}
3403

# 1) 10 countries with the lowest infant mortality rates

In [16]:
my_dict = {'name': [],
           'infant_mortality': []}


for country in root:
    
    try:
        infant_mortality_value = country.findtext("infant_mortality")
        my_dict["infant_mortality"].append(float(infant_mortality_value))
        
        name_value = country[0].text
        my_dict["name"].append(name_value)
        # print(infant_mortality_valuabse)
    except:
#         population_value = 0
#         my_dict["infant_mortality"].append(infant_mortality_value)
        pass

In [19]:
df = pd.DataFrame(my_dict)
df.sort_values(by=["infant_mortality"], ascending=False)

                         name  infant_mortality
178            Western Sahara            145.82
48                Afghanistan            117.23
173                      Mali            104.34
210                   Somalia            100.14
197  Central African Republic             92.86
..                        ...               ...
98                  Singapore              2.53
109                   Bermuda              2.48
34                     Norway              2.48
90                      Japan              2.13
36                     Monaco              1.81

[228 rows x 2 columns]

# 2) 10 cities with the largest population

In [24]:
pop = pd.read_xml("mondial.xml").head(5)

In [ ]:
def pop_extractor(querystring): #'country/province/city'
    pop_list = []
    for ele in tree.iterfind(querystring):
        temp = []
        for i in range(len(ele)):
            if ele[i].tag == ‘population’:
                temp.append(int(ele[i].text))
        pop_list.append(temp)
    pops_final = []
    for l in pop_list:
        if len(l) == 0:
            pops_final.append(0)
        else:
            pops_final.append(l[-1])
    return pops_final

In [65]:
pop2 = pop.transpose()
pop2

,0,1,2,3,4
car_code,AL,GR,MK,SRB,MNE
area,28750.0,131940.0,25333.0,77474.0,14026.0
capital,cty-Albania-Tirane,cty-Greece-Athens,cty-Macedonia-Skopje,city-Belgrade-SRB-SRB,city-Podgorica-MNE-MNE
memberships,org-BSEC org-CEI org-CD org-SELEC org-CE org-E...,org-AG org-BIS org-BSEC org-CD org-SELEC org-C...,org-BIS org-CEI org-CD org-SELEC org-CE org-EA...,org-BIS org-BSEC org-CEI org-CD org-SELEC org-...,org-CEI org-CD org-SELEC org-CE org-EAPC org-E...
name,Albania,Greece,North Macedonia,Serbia,Montenegro
population,2821977.0,10816286.0,2059794.0,7120666.0,620029.0
population_growth,0.3,0.01,0.21,-0.46,-0.49
infant_mortality,13.19,4.78,7.9,6.16,NaN
gdp_total,12800.0,243300.0,10650.0,43680.0,4518.0
gdp_agri,19.5,3.5,10.2,7.9,0.8
gdp_ind,12.0,16.0,27.5,31.8,11.3
gdp_serv,68.5,80.5,62.3,60.3,87.9
inflation,1.7,-0.8,2.8,2.2,4.0
unemployment,16.9,27.9,28.6,20.1,19.1
indep_date,1912-11-28,1829-01-01,1991-09-17,1992-04-11,2006-06-03
government,parliamentary democracy,parliamentary republic,parliamentary democracy,republic,republic
encompassed,NaN,NaN,NaN,NaN,NaN
ethnicgroup,Greek,Greek,Bosniak,Croat,Albanian
religion,Christian Orthodox,Muslim,Roman Catholic,Protestant,Roman Catholic
language,Greek,Greek,Serbian,Roma,Albanian
border,NaN,NaN,NaN,NaN,NaN
city,NaN,None,NaN,NaN,NaN
localname,None,Ελληνική Δημοκρατία,Република Cеверна Македонија,Република Србија,Црна Гора
province,NaN,NaN,NaN,NaN,NaN
dependent,NaN,NaN,NaN,NaN,NaN
id,None,None,None,None,None
headq,None,None,None,None,None
abbrev,None,None,None,None,None
established,None,None,None,None,None
members,NaN,NaN,NaN,NaN,NaN
country,None,None,None,None,None
bordering,None,None,None,None,None
located,NaN,NaN,NaN,NaN,NaN
depth,NaN,NaN,NaN,NaN,NaN
to,NaN,NaN,NaN,NaN,NaN
length,NaN,NaN,NaN,NaN,NaN
source,NaN,NaN,NaN,NaN,NaN
estuary,NaN,NaN,NaN,NaN,NaN
island,None,None,None,None,None
through,NaN,NaN,NaN,NaN,NaN
latitude,NaN,NaN,NaN,NaN,NaN
longitude,NaN,NaN,NaN,NaN,NaN
elevation,NaN,NaN,NaN,NaN,NaN
type,None,None,None,None,None
salinity,NaN,NaN,NaN,NaN,NaN
height,NaN,NaN,NaN,NaN,NaN
sea,None,None,None,None,None
islands,None,None,None,None,None
river,None,None,None,None,None
lake,None,None,None,None,None
last_eruption,None,None,None,None,None
mountains,None,None,None,None,None
iatacode,None,None,None,None,None
gmtOffset,NaN,NaN,NaN,NaN,NaN
located_on,NaN,NaN,NaN,NaN,NaN

In [71]:
pop3 = pop2.unstack()

In [80]:
pd.DataFrame(pop3)

                                                                 0
0 car_code                                                      AL
  area                                                     28750.0
  capital                                       cty-Albania-Tirane
  memberships    org-BSEC org-CEI org-CD org-SELEC org-CE org-E...
  name                                                     Albania
...                                                            ...
4 last_eruption                                               None
  mountains                                                   None
  iatacode                                                    None
  gmtOffset                                                   None
  located_on                                                  None

[275 rows x 1 columns]

In [81]:
# gave up

# 3) Question 3

In [83]:
rivers = {
    'length': [],
    'country': [],
    'name': []
}

for ele in tree.iterfind('river'):
    if ele.findall('length'):
        rivers['length'].append(float((ele.findall('length'))[0].text))
    else:
        rivers['length'].append(0)
    rivers['country'].append(ele.attrib["country"])
    rivers["name"].append((ele.attrib["id"]).split("-"))
    
rivers_db = pd.DataFrame(rivers)
rivers_db.groupby("country").max().sort_values(by="length",ascending=False).head(1)

         length                name
country
CN       6380.0  [river, YuanJiang]